# Import all models here so Alembic can detect them
# from app.models.iam import User, Membership, Session, InvitationCode, AccountRecoveryRequest
# from app.models.erp import AcademicYear, Period, Class, Enrollment, ...
# from app.models.lms import Course, Assignment, Submission, Grade, ...
# from app.models.com import ConsentPreference, Notification, ...
# from app.models.billing import Invoice, PaymentAttempt, ...
# from app.models.audit import AuditLog
