import 'package:flutter/material.dart';

// Generated from design-tokens/tokens.json.
// Do not edit this file manually. Run `make design-tokens`.

class AppColors {
  const AppColors._();

  static const primary = Color(0xFF2563EB);
  static const primaryLight = Color(0xFF60A5FA);
  static const primaryDark = Color(0xFF1D4ED8);
  static const secondary = Color(0xFF8B5CF6);
  static const accent = Color(0xFFF59E0B);
  static const success = Color(0xFF10B981);
  static const warning = Color(0xFFF59E0B);
  static const error = Color(0xFFEF4444);
  static const info = Color(0xFF0EA5E9);
  static const background = Color(0xFFF9FAFB);
  static const surface = Color(0xFFFFFFFF);
  static const border = Color(0xFFE5E7EB);
  static const text = Color(0xFF111827);
  static const textSecondary = Color(0xFF6B7280);
  static const successContainer = Color(0xFFDCFCE7);
  static const warningContainer = Color(0xFFFEF3C7);
  static const infoContainer = Color(0xFFDBEAFE);

  static const chartPalette = <Color>[
    success,
    warning,
    error,
    info,
    secondary,
    primary,
    Color(0xFF8B5CF6),
    Color(0xFF14B8A6),
  ];

  static const subjectColors = <String, Color>{
    'math': Color(0xFFEFF6FF),
    'french': Color(0xFFFEF3C7),
    'arabic': Color(0xFFECFDF5),
    'science': Color(0xFFF0FDF4),
    'history': Color(0xFFFAF5FF),
    'geography': Color(0xFFFFF7ED),
    'english': Color(0xFFFDF2F8),
    'islamic_studies': Color(0xFFF0F9FF),
    'art': Color(0xFFFEFCE8),
    'sport': Color(0xFFF0FDFA),
    'default': Color(0xFFF3F4F6),
  };

  static const roleAccents = <String, Color>{
    'ADM': Color(0xFF2563EB),
    'DIR': Color(0xFF4F46E5),
    'TCH': Color(0xFF10B981),
    'PAR': Color(0xFFF59E0B),
    'STD': Color(0xFF7C3AED),
    'EDUCATOR': Color(0xFFF97316),
    'CONTENT_MGR': Color(0xFF8B5CF6),
    'CMS': Color(0xFF8B5CF6),
    'SUP': Color(0xFF64748B),
    'SYS': Color(0xFF64748B),
    'default': Color(0xFF2563EB),
  };

  static Color roleAccentFor(String? role) {
    final key = (role ?? '').toUpperCase();
    return roleAccents[key] ?? roleAccents['default']!;
  }

  static const darkPrimary = Color(0xFF6B8AFF);
  static const darkPrimaryLight = Color(0xFF8BA4FF);
  static const darkPrimaryDark = Color(0xFF4A6AE5);
  static const darkSecondary = Color(0xFFA78BFA);
  static const darkSuccess = Color(0xFF34D399);
  static const darkSuccessContainer = Color(0xFF14532D);
  static const darkWarning = Color(0xFFFBBF24);
  static const darkWarningContainer = Color(0xFF78350F);
  static const darkInfo = Color(0xFF60A5FA);
  static const darkInfoContainer = Color(0xFF1E3A8A);
  static const darkBackground = Color(0xFF0F172A);
  static const darkSurface = Color(0xFF1E293B);
  static const darkBorder = Color(0xFF334155);
  static const darkText = Color(0xFFF1F5F9);
  static const darkTextSecondary = Color(0xFF94A3B8);
  static const darkChartPalette = <Color>[
    darkSuccess,
    darkWarning,
    error,
    darkInfo,
    darkSecondary,
    darkPrimary,
    Color(0xFFC084FC),
    Color(0xFF2DD4BF),
  ];

  static const darkSubjectColors = <String, Color>{
    'math': Color(0xFF1E3A8A),
    'french': Color(0xFF78350F),
    'arabic': Color(0xFF14532D),
    'science': Color(0xFF166534),
    'history': Color(0xFF581C87),
    'geography': Color(0xFF7C2D12),
    'english': Color(0xFF831843),
    'islamic_studies': Color(0xFF0C4A6E),
    'art': Color(0xFF713F12),
    'sport': Color(0xFF134E4A),
    'default': Color(0xFF334155),
  };
}

@immutable
class SchoolModeColors extends ThemeExtension<SchoolModeColors> {
  final Color background;
  final Color surface;
  final Color surfaceSoft;
  final Color text;
  final Color textSecondary;
  final Color border;
  final Color accent;
  final Color accentSoft;

  const SchoolModeColors({
    required this.background,
    required this.surface,
    required this.surfaceSoft,
    required this.text,
    required this.textSecondary,
    required this.border,
    required this.accent,
    required this.accentSoft,
  });

  static const formal = SchoolModeColors(
    background: Color(0xFFF9FAFB),
    surface: Color(0xFFFFFFFF),
    surfaceSoft: Color(0xFFF3F4F6),
    text: Color(0xFF111827),
    textSecondary: Color(0xFF6B7280),
    border: Color(0xFFE5E7EB),
    accent: Color(0xFF2563EB),
    accentSoft: Color(0xFFDBEAFE),
  );

  static const informal = SchoolModeColors(
    background: Color(0xFFFFF7ED),
    surface: Color(0xFFFFFFFF),
    surfaceSoft: Color(0xFFFFFBEB),
    text: Color(0xFF3D2C1E),
    textSecondary: Color(0xFF7C5B3E),
    border: Color(0xFFFED7AA),
    accent: Color(0xFFF97316),
    accentSoft: Color(0xFFFFEDD5),
  );

  @override
  SchoolModeColors copyWith({
    Color? background,
    Color? surface,
    Color? surfaceSoft,
    Color? text,
    Color? textSecondary,
    Color? border,
    Color? accent,
    Color? accentSoft,
  }) {
    return SchoolModeColors(
      background: background ?? this.background,
      surface: surface ?? this.surface,
      surfaceSoft: surfaceSoft ?? this.surfaceSoft,
      text: text ?? this.text,
      textSecondary: textSecondary ?? this.textSecondary,
      border: border ?? this.border,
      accent: accent ?? this.accent,
      accentSoft: accentSoft ?? this.accentSoft,
    );
  }

  @override
  SchoolModeColors lerp(ThemeExtension<SchoolModeColors>? other, double t) {
    if (other is! SchoolModeColors) return this;
    return SchoolModeColors(
      background: Color.lerp(background, other.background, t) ?? background,
      surface: Color.lerp(surface, other.surface, t) ?? surface,
      surfaceSoft: Color.lerp(surfaceSoft, other.surfaceSoft, t) ?? surfaceSoft,
      text: Color.lerp(text, other.text, t) ?? text,
      textSecondary:
          Color.lerp(textSecondary, other.textSecondary, t) ?? textSecondary,
      border: Color.lerp(border, other.border, t) ?? border,
      accent: Color.lerp(accent, other.accent, t) ?? accent,
      accentSoft: Color.lerp(accentSoft, other.accentSoft, t) ?? accentSoft,
    );
  }
}

@immutable
class StudentTierColors extends ThemeExtension<StudentTierColors> {
  final Color background;
  final Color surface;
  final Color accent;
  final Color accentSoft;
  final Color text;
  final Color border;

  const StudentTierColors({
    required this.background,
    required this.surface,
    required this.accent,
    required this.accentSoft,
    required this.text,
    required this.border,
  });

  static const maternelle = StudentTierColors(
    background: Color(0xFFFFF7ED),
    surface: Color(0xFFFFFFFF),
    accent: Color(0xFFF97316),
    accentSoft: Color(0xFFFFEDD5),
    text: Color(0xFF3D2C1E),
    border: Color(0xFFFED7AA),
  );

  static const primaire = StudentTierColors(
    background: Color(0xFFFFF7ED),
    surface: Color(0xFFFFFFFF),
    accent: Color(0xFF7C3AED),
    accentSoft: Color(0xFFEDE9FE),
    text: Color(0xFF1F1035),
    border: Color(0xFFE9D5FF),
  );

  static const college = StudentTierColors(
    background: Color(0xFFF8FAFC),
    surface: Color(0xFFFFFFFF),
    accent: Color(0xFF2563EB),
    accentSoft: Color(0xFFDBEAFE),
    text: Color(0xFF111827),
    border: Color(0xFFE5E7EB),
  );

  @override
  StudentTierColors copyWith({
    Color? background,
    Color? surface,
    Color? accent,
    Color? accentSoft,
    Color? text,
    Color? border,
  }) {
    return StudentTierColors(
      background: background ?? this.background,
      surface: surface ?? this.surface,
      accent: accent ?? this.accent,
      accentSoft: accentSoft ?? this.accentSoft,
      text: text ?? this.text,
      border: border ?? this.border,
    );
  }

  @override
  StudentTierColors lerp(ThemeExtension<StudentTierColors>? other, double t) {
    if (other is! StudentTierColors) return this;
    return StudentTierColors(
      background: Color.lerp(background, other.background, t) ?? background,
      surface: Color.lerp(surface, other.surface, t) ?? surface,
      accent: Color.lerp(accent, other.accent, t) ?? accent,
      accentSoft: Color.lerp(accentSoft, other.accentSoft, t) ?? accentSoft,
      text: Color.lerp(text, other.text, t) ?? text,
      border: Color.lerp(border, other.border, t) ?? border,
    );
  }
}

@immutable
class AppThemeColors extends ThemeExtension<AppThemeColors> {
  final Color success;
  final Color successContainer;
  final Color warning;
  final Color warningContainer;
  final Color info;
  final Color infoContainer;
  final List<Color> chartPalette;
  final Map<String, Color> subjectColors;

  const AppThemeColors({
    required this.success,
    required this.successContainer,
    required this.warning,
    required this.warningContainer,
    required this.info,
    required this.infoContainer,
    required this.chartPalette,
    required this.subjectColors,
  });

  static const light = AppThemeColors(
    success: AppColors.success,
    successContainer: AppColors.successContainer,
    warning: AppColors.warning,
    warningContainer: AppColors.warningContainer,
    info: AppColors.info,
    infoContainer: AppColors.infoContainer,
    chartPalette: AppColors.chartPalette,
    subjectColors: AppColors.subjectColors,
  );

  static const dark = AppThemeColors(
    success: AppColors.darkSuccess,
    successContainer: AppColors.darkSuccessContainer,
    warning: AppColors.darkWarning,
    warningContainer: AppColors.darkWarningContainer,
    info: AppColors.darkInfo,
    infoContainer: AppColors.darkInfoContainer,
    chartPalette: AppColors.darkChartPalette,
    subjectColors: AppColors.darkSubjectColors,
  );

  @override
  AppThemeColors copyWith({
    Color? success,
    Color? successContainer,
    Color? warning,
    Color? warningContainer,
    Color? info,
    Color? infoContainer,
    List<Color>? chartPalette,
    Map<String, Color>? subjectColors,
  }) {
    return AppThemeColors(
      success: success ?? this.success,
      successContainer: successContainer ?? this.successContainer,
      warning: warning ?? this.warning,
      warningContainer: warningContainer ?? this.warningContainer,
      info: info ?? this.info,
      infoContainer: infoContainer ?? this.infoContainer,
      chartPalette: chartPalette ?? this.chartPalette,
      subjectColors: subjectColors ?? this.subjectColors,
    );
  }

  @override
  AppThemeColors lerp(ThemeExtension<AppThemeColors>? other, double t) {
    if (other is! AppThemeColors) {
      return this;
    }
    return AppThemeColors(
      success: Color.lerp(success, other.success, t) ?? success,
      successContainer:
          Color.lerp(successContainer, other.successContainer, t) ??
              successContainer,
      warning: Color.lerp(warning, other.warning, t) ?? warning,
      warningContainer:
          Color.lerp(warningContainer, other.warningContainer, t) ??
              warningContainer,
      info: Color.lerp(info, other.info, t) ?? info,
      infoContainer:
          Color.lerp(infoContainer, other.infoContainer, t) ?? infoContainer,
      chartPalette: t < 0.5 ? chartPalette : other.chartPalette,
      subjectColors: t < 0.5 ? subjectColors : other.subjectColors,
    );
  }
}

@immutable
class KidsThemeColors extends ThemeExtension<KidsThemeColors> {
  final Color background;
  final Color backgroundSecondary;
  final Color surface;
  final Color primary;
  final Color primaryLight;
  final Color primaryDark;
  final Color text;
  final Color textSecondary;
  final Color border;
  final Color xp;
  final Color xpBarBackground;
  final Color level;
  final Color streak;

  const KidsThemeColors({
    required this.background,
    required this.backgroundSecondary,
    required this.surface,
    required this.primary,
    required this.primaryLight,
    required this.primaryDark,
    required this.text,
    required this.textSecondary,
    required this.border,
    required this.xp,
    required this.xpBarBackground,
    required this.level,
    required this.streak,
  });

  static const light = KidsThemeColors(
    background: Color(0xFFFFF7ED),
    backgroundSecondary: Color(0xFFFEF3C7),
    surface: Color(0xFFFFFFFF),
    primary: Color(0xFF7C3AED),
    primaryLight: Color(0xFFA78BFA),
    primaryDark: Color(0xFF5B21B6),
    text: Color(0xFF1F1035),
    textSecondary: Color(0xFF6D5A8A),
    border: Color(0xFFE9D5FF),
    xp: Color(0xFF3B82F6),
    xpBarBackground: Color(0xFFDBEAFE),
    level: Color(0xFF7C3AED),
    streak: Color(0xFFF97316),
  );

  static const dark = KidsThemeColors(
    background: Color(0xFF1F1633),
    backgroundSecondary: Color(0xFF2D2146),
    surface: Color(0xFF2A2140),
    primary: Color(0xFFA78BFA),
    primaryLight: Color(0xFFC4B5FD),
    primaryDark: Color(0xFF7C3AED),
    text: Color(0xFFF7F3FF),
    textSecondary: Color(0xFFD8CCF4),
    border: Color(0xFF5B3F8F),
    xp: Color(0xFF3B82F6),
    xpBarBackground: Color(0xFFDBEAFE),
    level: Color(0xFF7C3AED),
    streak: Color(0xFFF97316),
  );

  @override
  KidsThemeColors copyWith({
    Color? background,
    Color? backgroundSecondary,
    Color? surface,
    Color? primary,
    Color? primaryLight,
    Color? primaryDark,
    Color? text,
    Color? textSecondary,
    Color? border,
    Color? xp,
    Color? xpBarBackground,
    Color? level,
    Color? streak,
  }) {
    return KidsThemeColors(
      background: background ?? this.background,
      backgroundSecondary: backgroundSecondary ?? this.backgroundSecondary,
      surface: surface ?? this.surface,
      primary: primary ?? this.primary,
      primaryLight: primaryLight ?? this.primaryLight,
      primaryDark: primaryDark ?? this.primaryDark,
      text: text ?? this.text,
      textSecondary: textSecondary ?? this.textSecondary,
      border: border ?? this.border,
      xp: xp ?? this.xp,
      xpBarBackground: xpBarBackground ?? this.xpBarBackground,
      level: level ?? this.level,
      streak: streak ?? this.streak,
    );
  }

  @override
  KidsThemeColors lerp(ThemeExtension<KidsThemeColors>? other, double t) {
    if (other is! KidsThemeColors) {
      return this;
    }
    return KidsThemeColors(
      background: Color.lerp(background, other.background, t) ?? background,
      backgroundSecondary:
          Color.lerp(backgroundSecondary, other.backgroundSecondary, t) ??
              backgroundSecondary,
      surface: Color.lerp(surface, other.surface, t) ?? surface,
      primary: Color.lerp(primary, other.primary, t) ?? primary,
      primaryLight:
          Color.lerp(primaryLight, other.primaryLight, t) ?? primaryLight,
      primaryDark:
          Color.lerp(primaryDark, other.primaryDark, t) ?? primaryDark,
      text: Color.lerp(text, other.text, t) ?? text,
      textSecondary:
          Color.lerp(textSecondary, other.textSecondary, t) ?? textSecondary,
      border: Color.lerp(border, other.border, t) ?? border,
      xp: Color.lerp(xp, other.xp, t) ?? xp,
      xpBarBackground:
          Color.lerp(xpBarBackground, other.xpBarBackground, t) ??
              xpBarBackground,
      level: Color.lerp(level, other.level, t) ?? level,
      streak: Color.lerp(streak, other.streak, t) ?? streak,
    );
  }
}

class KidsContentColors {
  const KidsContentColors._();

  static const storyBackground = Color(0xFFFFF8ED);
  static const storyPageTurn = Color(0xFFFF6B35);
  static const storyText = Color(0xFF3D2C1E);
  static const storyHighlight = Color(0xFFFFD93D);
  static const starGold = Color(0xFFFFD700);
  static const starSilver = Color(0xFFC0C0C0);
  static const starBronze = Color(0xFFCD7F32);
  static const xpBar = Color(0xFF3B82F6);
  static const xpBarBackground = Color(0xFFDBEAFE);
  static const levelBadge = Color(0xFF7C3AED);
  static const streakOrange = Color(0xFFF97316);
  static const gameBlue = Color(0xFF4FC3F7);
  static const gameGreen = Color(0xFF81C784);
  static const gamePurple = Color(0xFFCE93D8);
  static const gameYellow = Color(0xFFFFF176);
  static const gameRed = Color(0xFFEF9A9A);
  static const gameCardBack = Color(0xFFB39DDB);
  static const canvasBackground = Color(0xFFFAFAFA);
  static const colorPickerBorder = Color(0xFFE0E0E0);
  static const samiPrimary = Color(0xFF4CAF50);
  static const samiSecondary = Color(0xFFFFEB3B);
  static const samiBubble = Color(0xFFF0FDF4);
  static const samiBubbleBorder = Color(0xFFBBF7D0);
  static const storyIntro = Color(0xFF7B1FA2);
  static const storyAlif = Color(0xFF43A047);
  static const storyBae = Color(0xFFEF6C00);
  static const storyZay = Color(0xFF1565C0);
  static const rewardGold = Color(0xFFFFB525);
  static const mascotPrimary = Color(0xFF6A1B9A);
}

extension AppThemeDataColors on ThemeData {
  AppThemeColors get semanticPalette =>
      extension<AppThemeColors>() ??
      (brightness == Brightness.dark
          ? AppThemeColors.dark
          : AppThemeColors.light);

  KidsThemeColors get kidsPalette =>
      extension<KidsThemeColors>() ??
      (brightness == Brightness.dark ? KidsThemeColors.dark : KidsThemeColors.light);
}
