/**
 * Design tokens - generated from design-tokens/tokens.json.
 * Do not edit this file manually. Run `make design-tokens`.
 */

// -- Colors --

/** Core brand colors */
export const colors = {
  primary: '#2563eb',
  primaryLight: '#60a5fa',
  primaryDark: '#1d4ed8',
  primaryHover: '#1d4ed8',
  secondary: '#8b5cf6',
  accent: '#f59e0b',
  danger: '#ef4444',
  dangerHover: '#dc2626',
  error: '#ef4444',
  success: '#10b981',
  warning: '#f59e0b',
  info: '#0ea5e9'
} as const;

/** Surface & background colors - light mode */
export const light = {
  bg: '#f9fafb',
  surface: '#ffffff',
  text: '#111827',
  textSecondary: '#6b7280',
  inverseText: '#f8fafc',
  border: '#e5e7eb'
} as const;

/** Surface & background colors - dark mode */
export const dark = {
  primary: '#6b8aff',
  primaryLight: '#8ba4ff',
  primaryDark: '#4a6ae5',
  primaryHover: '#4a6ae5',
  secondary: '#a78bfa',
  accent: '#f59e0b',
  danger: '#f87171',
  dangerHover: '#ef4444',
  error: '#f87171',
  success: '#34d399',
  warning: '#fbbf24',
  info: '#60a5fa',
  bg: '#0f172a',
  surface: '#1e293b',
  text: '#f1f5f9',
  textSecondary: '#94a3b8',
  inverseText: '#0f172a',
  border: '#334155'
} as const;

/** Kids theme colors */
export const kids = {
  primary: '#7c3aed',
  primaryLight: '#a78bfa',
  primaryDark: '#5b21b6',
  primaryHover: '#5b21b6',
  bg: '#fff7ed',
  bgSecondary: '#fef3c7',
  surface: '#ffffff',
  text: '#1f1035',
  textSecondary: '#6d5a8a',
  border: '#e9d5ff',
  sidebarBg: '#5b21b6',
  sidebarText: '#ffffff',
  sidebarActive: 'rgba(255, 255, 255, 0.2)',
  sidebarHover: 'rgba(255, 255, 255, 0.12)'
} as const;

/** Kids theme colors - dark mode */
export const kidsDark = {
  primary: '#a78bfa',
  primaryLight: '#c4b5fd',
  primaryDark: '#7c3aed',
  primaryHover: '#c4b5fd',
  bg: '#1f1633',
  bgSecondary: '#2d2146',
  surface: '#2a2140',
  text: '#f7f3ff',
  textSecondary: '#d8ccf4',
  border: '#5b3f8f',
  sidebarBg: '#2e1065',
  sidebarText: '#ffffff',
  sidebarActive: 'rgba(255, 255, 255, 0.22)',
  sidebarHover: 'rgba(255, 255, 255, 0.14)'
} as const;

/** Gamification colors shared by web/mobile */
export const gamification = {
  stars: '#f59e0b',
  xp: '#3b82f6',
  xpBarBackground: '#dbeafe',
  level: '#7c3aed',
  streak: '#f97316'
} as const;

/** Subject surface colors */
export const subjectColors = {
  math: '#eff6ff',
  french: '#fef3c7',
  arabic: '#ecfdf5',
  science: '#f0fdf4',
  history: '#faf5ff',
  geography: '#fff7ed',
  english: '#fdf2f8',
  islamic_studies: '#f0f9ff',
  art: '#fefce8',
  sport: '#f0fdfa',
  default: '#f3f4f6'
} as const;

/** Subject surface colors - dark mode */
export const darkSubjectColors = {
  math: '#1e3a8a',
  french: '#78350f',
  arabic: '#14532d',
  science: '#166534',
  history: '#581c87',
  geography: '#7c2d12',
  english: '#831843',
  islamic_studies: '#0c4a6e',
  art: '#713f12',
  sport: '#134e4a',
  default: '#334155'
} as const;

/** Role accent colors */
export const roleAccents = {
  ADM: '#2563eb',
  DIR: '#4f46e5',
  TCH: '#10b981',
  PAR: '#f59e0b',
  STD: '#7c3aed',
  EDUCATOR: '#f97316',
  CONTENT_MGR: '#8b5cf6',
  CMS: '#8b5cf6',
  SUP: '#64748b',
  SYS: '#64748b',
  default: '#2563eb'
} as const;

/** Micro-school warm identity */
export const microSchool = {
  bg: '#fff7ed',
  surface: '#ffffff',
  accent: '#f97316',
  accentSoft: '#ffedd5',
  success: '#10b981',
  border: '#fed7aa',
  text: '#3d2c1e'
} as const;

/** Formal/informal school design modes */
export const schoolModes = {
  formal: {
    bg: '#f9fafb',
    surface: '#ffffff',
    surfaceSoft: '#f3f4f6',
    text: '#111827',
    textSecondary: '#6b7280',
    border: '#e5e7eb',
    accent: '#2563eb',
    accentSoft: '#dbeafe'
  },
  informal: {
    bg: '#fff7ed',
    surface: '#ffffff',
    surfaceSoft: '#fffbeb',
    text: '#3d2c1e',
    textSecondary: '#7c5b3e',
    border: '#fed7aa',
    accent: '#f97316',
    accentSoft: '#ffedd5'
  }
} as const;

/** Student age/niveau tier palettes */
export const studentTiers = {
  maternelle: {
    bg: '#fff7ed',
    surface: '#ffffff',
    accent: '#f97316',
    accentSoft: '#ffedd5',
    text: '#3d2c1e',
    border: '#fed7aa'
  },
  primaire: {
    bg: '#fff7ed',
    surface: '#ffffff',
    accent: '#7c3aed',
    accentSoft: '#ede9fe',
    text: '#1f1035',
    border: '#e9d5ff'
  },
  college: {
    bg: '#f8fafc',
    surface: '#ffffff',
    accent: '#2563eb',
    accentSoft: '#dbeafe',
    text: '#111827',
    border: '#e5e7eb'
  }
} as const;

/** Kid-facing content colors */
export const kidsContent = {
  storyBackground: '#fff8ed',
  storyPageTurn: '#ff6b35',
  storyText: '#3d2c1e',
  storyHighlight: '#ffd93d',
  starGold: '#ffd700',
  starSilver: '#c0c0c0',
  starBronze: '#cd7f32',
  xpBar: '#3b82f6',
  xpBarBackground: '#dbeafe',
  levelBadge: '#7c3aed',
  streakOrange: '#f97316',
  gameBlue: '#4fc3f7',
  gameGreen: '#81c784',
  gamePurple: '#ce93d8',
  gameYellow: '#fff176',
  gameRed: '#ef9a9a',
  gameCardBack: '#b39ddb',
  canvasBackground: '#fafafa',
  colorPickerBorder: '#e0e0e0',
  samiPrimary: '#4caf50',
  samiSecondary: '#ffeb3b',
  samiBubble: '#f0fdf4',
  samiBubbleBorder: '#bbf7d0',
  storyIntro: '#7b1fa2',
  storyAlif: '#43a047',
  storyBae: '#ef6c00',
  storyZay: '#1565c0',
  rewardGold: '#ffb525',
  mascotPrimary: '#6a1b9a'
} as const;

export type SubjectColorTheme = 'light' | 'dark' | 'kids' | 'kids-dark';

export function getSubjectColor(subject: string | null | undefined, theme: SubjectColorTheme = 'light') {
  const key = normalizeTokenKey(subject);
  const palette = theme === 'dark' || theme === 'kids-dark' ? darkSubjectColors : subjectColors;
  return palette[key as keyof typeof palette] ?? palette.default;
}

export function getRoleAccent(role: string | null | undefined) {
  const key = (role ?? '').toUpperCase();
  return roleAccents[key as keyof typeof roleAccents] ?? roleAccents.default;
}

function normalizeTokenKey(value: string | null | undefined) {
  return (value ?? 'default')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[\s-]+/g, '_');
}

/** Chart colors for data visualization */
export const chart = {
  1: colors.primary,
  2: colors.success,
  3: colors.accent,
  4: colors.secondary,
  5: colors.info,
  6: colors.error,
} as const;

/** CSS var() shorthands for colors in inline style props */
export const colorVars = {
  primary: 'var(--color-primary)',
  primaryLight: 'var(--color-primary-light)',
  primaryDark: 'var(--color-primary-dark)',
  secondary: 'var(--color-secondary)',
  accent: 'var(--color-accent)',
  danger: 'var(--color-danger)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
  info: 'var(--color-info)',
  bg: 'var(--color-bg)',
  surface: 'var(--color-surface)',
  text: 'var(--color-text)',
  textSecondary: 'var(--color-text-secondary)',
  border: 'var(--color-border)',
} as const;

// -- Shadows --

export const shadows = {
  sm: 'var(--shadow-sm)',
  md: 'var(--shadow-md)',
  lg: 'var(--shadow-lg)',
  xl: 'var(--shadow-xl)',
  glowPrimary: 'var(--shadow-glow-primary)',
} as const;

export const shadowValues = {
  sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
  md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
  lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
  xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
} as const;

// -- Typography --

export const fontFamily = "'Cairo', sans-serif" as const;

export const fontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  md: 18,
  lg: 20,
  xl: 24,
  '2xl': 28,
} as const;

export const fontWeight = {
  normal: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
} as const;

export const lineHeight = {
  tight: 1.25,
  normal: 1.5,
  relaxed: 1.625,
} as const;

// -- Spacing --

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  base: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const radii = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 999,
} as const;

export const space = {
  xs: 'var(--space-xs)',
  sm: 'var(--space-sm)',
  md: 'var(--space-md)',
  base: 'var(--space-base)',
  lg: 'var(--space-lg)',
  xl: 'var(--space-xl)',
  xxl: 'var(--space-xxl)',
} as const;

export const radius = {
  sm: 'var(--radius-sm)',
  md: 'var(--radius-md)',
  lg: 'var(--radius-lg)',
  xl: 'var(--radius-xl)',
  full: 'var(--radius-full)',
} as const;

// -- Z-Index Scale --

export const zIndex = {
  base: 0,
  dropdown: 100,
  sticky: 200,
  modal: 300,
  toast: 400,
  tooltip: 500,
} as const;

// -- Breakpoints --

export const breakpoints = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
} as const;

// -- Transitions --

export const transitions = {
  fast: '0.1s ease',
  normal: '0.15s ease',
  slow: '0.25s ease',
  bounce: '0.3s cubic-bezier(0.16, 1, 0.3, 1)',
} as const;
