"""add_failed_login_attempts_table

Revision ID: 5465fdab5ca4
Revises: add_phase11_security_columns
Create Date: 2026-05-13 08:47:50.176564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5465fdab5ca4'
down_revision: Union[str, None] = 'add_phase11_security_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login_attempts',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failed_login_attempts_email', 'failed_login_attempts', ['email'], unique=False)
    op.create_index('idx_failed_login_attempts_ip', 'failed_login_attempts', ['ip_address'], unique=False)
    op.create_index('idx_failed_login_attempts_school', 'failed_login_attempts', ['school_id'], unique=False)
    op.create_index('idx_failed_login_attempts_user', 'failed_login_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_failed_login_attempts_school_id'), 'failed_login_attempts', ['school_id'], unique=False)
    op.create_table('known_devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='uq_known_device_user_fingerprint')
    )
    op.create_index('idx_known_devices_fingerprint', 'known_devices', ['device_fingerprint'], unique=False)
    op.create_index('idx_known_devices_school', 'known_devices', ['school_id'], unique=False)
    op.create_index('idx_known_devices_user', 'known_devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_known_devices_school_id'), 'known_devices', ['school_id'], unique=False)
    op.create_table('known_locations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', name='uq_known_location_user_ip')
    )
    op.create_index('idx_known_locations_ip', 'known_locations', ['ip_address'], unique=False)
    op.create_index('idx_known_locations_school', 'known_locations', ['school_id'], unique=False)
    op.create_index('idx_known_locations_user', 'known_locations', ['user_id'], unique=False)
    op.create_index(op.f('ix_known_locations_school_id'), 'known_locations', ['school_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user_id')
    )
    op.create_index('idx_oauth_accounts_provider', 'oauth_accounts', ['provider'], unique=False)
    op.create_index('idx_oauth_accounts_school', 'oauth_accounts', ['school_id'], unique=False)
    op.create_index('idx_oauth_accounts_user', 'oauth_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_school_id'), 'oauth_accounts', ['school_id'], unique=False)
    op.create_table('password_history',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_password_history_school', 'password_history', ['school_id'], unique=False)
    op.create_index('idx_password_history_user', 'password_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_history_school_id'), 'password_history', ['school_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('transports', sa.String(length=100), nullable=True),
    sa.Column('is_backup', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('user_id', 'device_name', name='uq_webauthn_user_device_name')
    )
    op.create_index('idx_webauthn_credentials_school', 'webauthn_credentials', ['school_id'], unique=False)
    op.create_index('idx_webauthn_credentials_user', 'webauthn_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_webauthn_credentials_school_id'), 'webauthn_credentials', ['school_id'], unique=False)
    op.drop_index('idx_upload_sessions_created', table_name='upload_sessions')
    op.drop_index('idx_upload_sessions_school', table_name='upload_sessions')
    op.drop_index('idx_upload_sessions_state', table_name='upload_sessions')
    op.drop_index('idx_upload_sessions_uploader', table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index('idx_absence_justifications_attendance_record_id', table_name='absence_justifications')
    op.drop_index('idx_absence_justifications_parent_id', table_name='absence_justifications')
    op.create_index('idx_absence_justifications_attendance_record', 'absence_justifications', ['attendance_record_id'], unique=False)
    op.create_index('idx_absence_justifications_parent', 'absence_justifications', ['parent_id'], unique=False)
    op.drop_index('idx_academic_snapshots_taken_at', table_name='academic_snapshots')
    op.create_index('idx_academic_snapshots_taken_at', 'academic_snapshots', ['school_id', 'taken_at'], unique=False)
    op.create_index(op.f('ix_academic_snapshots_school_id'), 'academic_snapshots', ['school_id'], unique=False)
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.drop_index('idx_account_recovery_requests_school_id', table_name='account_recovery_requests')
    op.create_index('idx_recovery_school_id', 'account_recovery_requests', ['school_id'], unique=False)
    op.create_index(op.f('ix_account_recovery_requests_school_id'), 'account_recovery_requests', ['school_id'], unique=False)
    op.drop_index('idx_activities_search', table_name='activities', postgresql_using='gin')
    op.create_index(op.f('ix_activities_school_id'), 'activities', ['school_id'], unique=False)
    op.create_index(op.f('ix_admin_profiles_school_id'), 'admin_profiles', ['school_id'], unique=False)
    op.create_index(op.f('ix_ai_preferences_school_id'), 'ai_preferences', ['school_id'], unique=False)
    op.create_index(op.f('ix_announcements_school_id'), 'announcements', ['school_id'], unique=False)
    op.drop_index('idx_assessment_results_student_id', table_name='assessment_results')
    op.create_index('idx_assessment_results_student', 'assessment_results', ['student_id'], unique=False)
    op.drop_index('idx_assessments_search', table_name='assessments', postgresql_using='gin')
    op.drop_index('idx_assessments_teacher_id', table_name='assessments')
    op.create_index('idx_assessments_teacher', 'assessments', ['teacher_id'], unique=False)
    op.drop_index('idx_assignments_search', table_name='assignments', postgresql_using='gin')
    op.drop_index('idx_assignments_teacher_id', table_name='assignments')
    op.create_index('idx_assignments_teacher', 'assignments', ['teacher_id'], unique=False)
    op.drop_index('idx_attendance_alerts_period_id', table_name='attendance_alerts')
    op.create_index(op.f('ix_attendance_alerts_school_id'), 'attendance_alerts', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_school_id'), 'attendance_records', ['school_id'], unique=False)
    op.drop_index('idx_attendance_sessions_class_id', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_period_id', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_teacher_id', table_name='attendance_sessions')
    op.create_index('idx_attendance_sessions_class', 'attendance_sessions', ['class_id'], unique=False)
    op.create_index('idx_attendance_sessions_period', 'attendance_sessions', ['period_id'], unique=False)
    op.create_index('idx_attendance_sessions_teacher', 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.drop_index('idx_class_content_assignments_content_item_id', table_name='class_content_assignments')
    op.create_index('idx_class_content_assignments_content_item', 'class_content_assignments', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_class_content_assignments_school_id'), 'class_content_assignments', ['school_id'], unique=False)
    op.drop_index('idx_classes_academic_year_id', table_name='classes')
    op.create_index('idx_classes_academic_year', 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_school_id'), 'compliance_reports', ['school_id'], unique=False)
    op.create_index(op.f('ix_consent_preferences_school_id'), 'consent_preferences', ['school_id'], unique=False)
    op.drop_index('idx_content_item_assets_content_item_id', table_name='content_item_assets')
    op.create_index('idx_content_item_assets_content_item', 'content_item_assets', ['content_item_id'], unique=False)
    op.drop_index('idx_content_items_original_content_id', table_name='content_items')
    op.drop_index('idx_content_items_school_id', table_name='content_items')
    op.drop_index('idx_content_items_search', table_name='content_items', postgresql_using='gin')
    op.create_index('idx_content_items_original', 'content_items', ['original_content_id'], unique=False)
    op.create_index('idx_content_items_school', 'content_items', ['school_id'], unique=False)
    op.create_index(op.f('ix_content_items_school_id'), 'content_items', ['school_id'], unique=False)
    op.create_index(op.f('ix_content_manager_profiles_school_id'), 'content_manager_profiles', ['school_id'], unique=False)
    op.drop_index('idx_content_submissions_content_item_id', table_name='content_submissions')
    op.drop_index('idx_content_submissions_promoted_content_id', table_name='content_submissions')
    op.create_index('idx_content_submissions_content_item', 'content_submissions', ['content_item_id'], unique=False)
    op.create_index('idx_content_submissions_promoted_content', 'content_submissions', ['promoted_content_id'], unique=False)
    op.create_index(op.f('ix_content_submissions_school_id'), 'content_submissions', ['school_id'], unique=False)
    op.create_index(op.f('ix_conversations_school_id'), 'conversations', ['school_id'], unique=False)
    op.drop_index('idx_courses_search', table_name='courses', postgresql_using='gin')
    op.drop_index('idx_courses_teacher_id', table_name='courses')
    op.create_index('idx_courses_teacher', 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_courses_school_id'), 'courses', ['school_id'], unique=False)
    op.create_index(op.f('ix_curriculum_mappings_school_id'), 'curriculum_mappings', ['school_id'], unique=False)
    op.create_index(op.f('ix_data_exports_school_id'), 'data_exports', ['school_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_school_id'), 'device_tokens', ['school_id'], unique=False)
    op.alter_column('difficulty_adaptations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_document_versions_uploader_id', table_name='document_versions')
    op.create_index('idx_doc_versions_uploader_id', 'document_versions', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_documents_school_id'), 'documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_eligibility_rules_school_id'), 'eligibility_rules', ['school_id'], unique=False)
    op.drop_index('idx_enrollments_class_id', table_name='enrollments')
    op.drop_index('idx_enrollments_program_version', table_name='enrollments')
    op.create_index('idx_enrollments_class', 'enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrollments_school_id'), 'enrollments', ['school_id'], unique=False)
    op.create_index(op.f('ix_event_reminder_preferences_school_id'), 'event_reminder_preferences', ['school_id'], unique=False)
    op.create_index(op.f('ix_events_school_id'), 'events', ['school_id'], unique=False)
    op.drop_index('idx_fee_assignments_fee_structure_id', table_name='fee_assignments')
    op.create_index('idx_fee_assignments_fee_structure', 'fee_assignments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_assignments_school_id'), 'fee_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_school_id'), 'fee_structures', ['school_id'], unique=False)
    op.alter_column('game_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_grade_categories_school_id', table_name='grade_categories')
    op.create_index('idx_grade_categories_school', 'grade_categories', ['school_id'], unique=False)
    op.create_index(op.f('ix_grade_categories_school_id'), 'grade_categories', ['school_id'], unique=False)
    op.drop_index('idx_grades_submission_id', table_name='grades')
    op.drop_index('idx_grades_teacher_id', table_name='grades')
    op.create_index('idx_grades_teacher', 'grades', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_invitation_codes_school_id'), 'invitation_codes', ['school_id'], unique=False)
    op.alter_column('invoice_items', 'tva_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoice_items', 'tva_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.drop_index('idx_invoice_items_invoice_id', table_name='invoice_items')
    op.create_index('idx_invoice_items_invoice', 'invoice_items', ['invoice_id'], unique=False)
    op.drop_index('idx_invoices_fee_structure_id', table_name='invoices')
    op.create_index('idx_invoices_fee_structure', 'invoices', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_invoices_school_id'), 'invoices', ['school_id'], unique=False)
    op.drop_index('idx_justification_reviews_justification_id', table_name='justification_reviews')
    op.drop_index('idx_justification_reviews_reviewer_id', table_name='justification_reviews')
    op.create_index('idx_justification_reviews_justification', 'justification_reviews', ['justification_id'], unique=False)
    op.create_index('idx_justification_reviews_reviewer', 'justification_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_late_fee_policies_school_id'), 'late_fee_policies', ['school_id'], unique=False)
    op.create_index('uq_level_age_mappings_code_platform', 'level_age_mappings', ['level_code'], unique=True, postgresql_where='school_id IS NULL')
    op.create_index(op.f('ix_login_history_school_id'), 'login_history', ['school_id'], unique=False)
    op.drop_index('idx_messages_body_gin', table_name='messages', postgresql_using='gin')
    op.create_index('idx_micro_budgets_created_by', 'micro_budgets', ['created_by'], unique=False)
    op.create_index(op.f('ix_micro_budgets_school_id'), 'micro_budgets', ['school_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_school_id'), 'notification_deliveries', ['school_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_school_id'), 'notification_preferences', ['school_id'], unique=False)
    op.drop_index('idx_notifications_school_parent', table_name='notifications')
    op.drop_index('idx_notifications_search', table_name='notifications', postgresql_using='gin')
    op.create_index(op.f('ix_notifications_school_id'), 'notifications', ['school_id'], unique=False)
    op.drop_index('idx_parent_feed_items_search', table_name='parent_feed_items', postgresql_using='gin')
    op.drop_index('idx_parent_feed_items_student_id', table_name='parent_feed_items')
    op.create_index('idx_feed_student_id', 'parent_feed_items', ['student_id'], unique=False)
    op.create_index(op.f('ix_parent_feed_items_school_id'), 'parent_feed_items', ['school_id'], unique=False)
    op.alter_column('parent_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_parent_profiles_school_id'), 'parent_profiles', ['school_id'], unique=False)
    op.drop_index('idx_payment_attempts_parent_id', table_name='payment_attempts')
    op.drop_index('idx_payment_attempts_school_id', table_name='payment_attempts')
    op.create_index('idx_payment_attempts_parent', 'payment_attempts', ['parent_id'], unique=False)
    op.create_index('idx_payment_attempts_school', 'payment_attempts', ['school_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_school_id'), 'payment_attempts', ['school_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_school_id'), 'payment_plans', ['school_id'], unique=False)
    op.drop_index('idx_payment_proofs_payment_attempt_id', table_name='payment_proofs')
    op.create_index('idx_payment_proofs_payment_attempt', 'payment_proofs', ['payment_attempt_id'], unique=False)
    op.create_index(op.f('ix_periods_school_id'), 'periods', ['school_id'], unique=False)
    op.drop_index('idx_prog_events_to_version', table_name='program_assignment_events')
    op.drop_index('idx_prog_events_school_student_occurred', table_name='program_assignment_events')
    op.create_index('idx_prog_events_school_student_occurred', 'program_assignment_events', ['school_id', 'student_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_program_assignment_events_school_id'), 'program_assignment_events', ['school_id'], unique=False)
    op.create_index(op.f('ix_program_equivalences_school_id'), 'program_equivalences', ['school_id'], unique=False)
    op.create_index(op.f('ix_program_versions_school_id'), 'program_versions', ['school_id'], unique=False)
    op.create_index(op.f('ix_programs_school_id'), 'programs', ['school_id'], unique=False)
    op.drop_index('idx_provider_webhook_events_payment_attempt_id', table_name='provider_webhook_events')
    op.create_index('idx_provider_webhook_events_payment_attempt', 'provider_webhook_events', ['payment_attempt_id'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_school_id'), 'provider_webhook_events', ['school_id'], unique=False)
    op.create_index(op.f('ix_question_bank_items_school_id'), 'question_bank_items', ['school_id'], unique=False)
    op.drop_index('idx_quiz_responses_question_id', table_name='quiz_responses')
    op.create_index('idx_quiz_responses_question', 'quiz_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes_school_id'), 'quizzes', ['school_id'], unique=False)
    op.create_index(op.f('ix_report_jobs_school_id'), 'report_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_report_schedules_school_id'), 'report_schedules', ['school_id'], unique=False)
    op.drop_index('idx_resources_search_gin', table_name='resources', postgresql_using='gin')
    op.create_index(op.f('ix_resources_school_id'), 'resources', ['school_id'], unique=False)
    op.drop_index('idx_rubric_scores_criterion_id', table_name='rubric_scores')
    op.drop_index('idx_rubric_scores_level_id', table_name='rubric_scores')
    op.create_index('idx_rubric_scores_criterion', 'rubric_scores', ['criterion_id'], unique=False)
    op.create_index('idx_rubric_scores_level', 'rubric_scores', ['level_id'], unique=False)
    op.create_index(op.f('ix_rubrics_school_id'), 'rubrics', ['school_id'], unique=False)
    op.create_index(op.f('ix_sessions_school_id'), 'sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_sibling_discount_policies_school_id'), 'sibling_discount_policies', ['school_id'], unique=False)
    op.create_index(op.f('ix_skill_passports_school_id'), 'skill_passports', ['school_id'], unique=False)
    op.create_index(op.f('ix_skill_progress_school_id'), 'skill_progress', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_document_requirements_school_id'), 'student_document_requirements', ['school_id'], unique=False)
    op.drop_index('idx_student_period_averages_school_id', table_name='student_period_averages')
    op.drop_index('idx_student_period_averages_student_id', table_name='student_period_averages')
    op.create_index('idx_spa_school', 'student_period_averages', ['school_id'], unique=False)
    op.create_index('idx_spa_student', 'student_period_averages', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_period_averages_school_id'), 'student_period_averages', ['school_id'], unique=False)
    op.alter_column('student_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_student_profiles_school_id'), 'student_profiles', ['school_id'], unique=False)
    op.alter_column('student_rewards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_submission_files_submission_id', table_name='submission_files')
    op.create_index('idx_submission_files_submission', 'submission_files', ['submission_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_school_id'), 'teacher_assignments', ['school_id'], unique=False)
    op.alter_column('teacher_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_teacher_profiles_school_id'), 'teacher_profiles', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_constraints_school_id'), 'timetable_constraints', ['school_id'], unique=False)
    op.drop_index('idx_timetable_exceptions_substitute_teacher_id', table_name='timetable_exceptions')
    op.drop_index('idx_timetable_exceptions_timetable_slot_id', table_name='timetable_exceptions')
    op.create_index('idx_timetable_exceptions_substitute_teacher', 'timetable_exceptions', ['substitute_teacher_id'], unique=False)
    op.create_index('idx_timetable_exceptions_timetable_slot', 'timetable_exceptions', ['timetable_slot_id'], unique=False)
    op.create_index(op.f('ix_timetable_exceptions_school_id'), 'timetable_exceptions', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_generation_jobs_school_id'), 'timetable_generation_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_school_id'), 'timetable_slots', ['school_id'], unique=False)
    op.create_index(op.f('ix_writing_attempts_school_id'), 'writing_attempts', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_attempts_school_id'), table_name='writing_attempts')
    op.drop_index(op.f('ix_timetable_slots_school_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_generation_jobs_school_id'), table_name='timetable_generation_jobs')
    op.drop_index(op.f('ix_timetable_exceptions_school_id'), table_name='timetable_exceptions')
    op.drop_index('idx_timetable_exceptions_timetable_slot', table_name='timetable_exceptions')
    op.drop_index('idx_timetable_exceptions_substitute_teacher', table_name='timetable_exceptions')
    op.create_index('idx_timetable_exceptions_timetable_slot_id', 'timetable_exceptions', ['timetable_slot_id'], unique=False)
    op.create_index('idx_timetable_exceptions_substitute_teacher_id', 'timetable_exceptions', ['substitute_teacher_id'], unique=False)
    op.drop_index(op.f('ix_timetable_constraints_school_id'), table_name='timetable_constraints')
    op.drop_index(op.f('ix_teacher_profiles_school_id'), table_name='teacher_profiles')
    op.alter_column('teacher_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_teacher_assignments_school_id'), table_name='teacher_assignments')
    op.drop_index('idx_submission_files_submission', table_name='submission_files')
    op.create_index('idx_submission_files_submission_id', 'submission_files', ['submission_id'], unique=False)
    op.alter_column('student_rewards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_profiles_school_id'), table_name='student_profiles')
    op.alter_column('student_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_period_averages_school_id'), table_name='student_period_averages')
    op.drop_index('idx_spa_student', table_name='student_period_averages')
    op.drop_index('idx_spa_school', table_name='student_period_averages')
    op.create_index('idx_student_period_averages_student_id', 'student_period_averages', ['student_id'], unique=False)
    op.create_index('idx_student_period_averages_school_id', 'student_period_averages', ['school_id'], unique=False)
    op.drop_index(op.f('ix_student_document_requirements_school_id'), table_name='student_document_requirements')
    op.drop_index(op.f('ix_skill_progress_school_id'), table_name='skill_progress')
    op.drop_index(op.f('ix_skill_passports_school_id'), table_name='skill_passports')
    op.drop_index(op.f('ix_sibling_discount_policies_school_id'), table_name='sibling_discount_policies')
    op.drop_index(op.f('ix_sessions_school_id'), table_name='sessions')
    op.drop_index(op.f('ix_rubrics_school_id'), table_name='rubrics')
    op.drop_index('idx_rubric_scores_level', table_name='rubric_scores')
    op.drop_index('idx_rubric_scores_criterion', table_name='rubric_scores')
    op.create_index('idx_rubric_scores_level_id', 'rubric_scores', ['level_id'], unique=False)
    op.create_index('idx_rubric_scores_criterion_id', 'rubric_scores', ['criterion_id'], unique=False)
    op.drop_index(op.f('ix_resources_school_id'), table_name='resources')
    op.create_index('idx_resources_search_gin', 'resources', ['tags'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_report_schedules_school_id'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_jobs_school_id'), table_name='report_jobs')
    op.drop_index(op.f('ix_quizzes_school_id'), table_name='quizzes')
    op.drop_index('idx_quiz_responses_question', table_name='quiz_responses')
    op.create_index('idx_quiz_responses_question_id', 'quiz_responses', ['question_id'], unique=False)
    op.drop_index(op.f('ix_question_bank_items_school_id'), table_name='question_bank_items')
    op.drop_index(op.f('ix_provider_webhook_events_school_id'), table_name='provider_webhook_events')
    op.drop_index('idx_provider_webhook_events_payment_attempt', table_name='provider_webhook_events')
    op.create_index('idx_provider_webhook_events_payment_attempt_id', 'provider_webhook_events', ['payment_attempt_id'], unique=False)
    op.drop_index(op.f('ix_programs_school_id'), table_name='programs')
    op.drop_index(op.f('ix_program_versions_school_id'), table_name='program_versions')
    op.drop_index(op.f('ix_program_equivalences_school_id'), table_name='program_equivalences')
    op.drop_index(op.f('ix_program_assignment_events_school_id'), table_name='program_assignment_events')
    op.drop_index('idx_prog_events_school_student_occurred', table_name='program_assignment_events')
    op.create_index('idx_prog_events_school_student_occurred', 'program_assignment_events', ['school_id', 'student_id', sa.text('occurred_at DESC')], unique=False)
    op.create_index('idx_prog_events_to_version', 'program_assignment_events', ['to_program_version_id'], unique=False)
    op.drop_index(op.f('ix_periods_school_id'), table_name='periods')
    op.drop_index('idx_payment_proofs_payment_attempt', table_name='payment_proofs')
    op.create_index('idx_payment_proofs_payment_attempt_id', 'payment_proofs', ['payment_attempt_id'], unique=False)
    op.drop_index(op.f('ix_payment_plans_school_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_attempts_school_id'), table_name='payment_attempts')
    op.drop_index('idx_payment_attempts_school', table_name='payment_attempts')
    op.drop_index('idx_payment_attempts_parent', table_name='payment_attempts')
    op.create_index('idx_payment_attempts_school_id', 'payment_attempts', ['school_id'], unique=False)
    op.create_index('idx_payment_attempts_parent_id', 'payment_attempts', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_parent_profiles_school_id'), table_name='parent_profiles')
    op.alter_column('parent_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_parent_feed_items_school_id'), table_name='parent_feed_items')
    op.drop_index('idx_feed_student_id', table_name='parent_feed_items')
    op.create_index('idx_parent_feed_items_student_id', 'parent_feed_items', ['student_id'], unique=False)
    op.create_index('idx_parent_feed_items_search', 'parent_feed_items', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_notifications_school_id'), table_name='notifications')
    op.create_index('idx_notifications_search', 'notifications', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_notifications_school_parent', 'notifications', ['school_id', 'parent_id'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_school_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_deliveries_school_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_micro_budgets_school_id'), table_name='micro_budgets')
    op.drop_index('idx_micro_budgets_created_by', table_name='micro_budgets')
    op.create_index('idx_messages_body_gin', 'messages', [sa.text("to_tsvector('simple'::regconfig, body)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_login_history_school_id'), table_name='login_history')
    op.drop_index('uq_level_age_mappings_code_platform', table_name='level_age_mappings', postgresql_where='school_id IS NULL')
    op.drop_index(op.f('ix_late_fee_policies_school_id'), table_name='late_fee_policies')
    op.drop_index('idx_justification_reviews_reviewer', table_name='justification_reviews')
    op.drop_index('idx_justification_reviews_justification', table_name='justification_reviews')
    op.create_index('idx_justification_reviews_reviewer_id', 'justification_reviews', ['reviewer_id'], unique=False)
    op.create_index('idx_justification_reviews_justification_id', 'justification_reviews', ['justification_id'], unique=False)
    op.drop_index(op.f('ix_invoices_school_id'), table_name='invoices')
    op.drop_index('idx_invoices_fee_structure', table_name='invoices')
    op.create_index('idx_invoices_fee_structure_id', 'invoices', ['fee_structure_id'], unique=False)
    op.drop_index('idx_invoice_items_invoice', table_name='invoice_items')
    op.create_index('idx_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.alter_column('invoice_items', 'tva_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoice_items', 'tva_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_index(op.f('ix_invitation_codes_school_id'), table_name='invitation_codes')
    op.drop_index('idx_grades_teacher', table_name='grades')
    op.create_index('idx_grades_teacher_id', 'grades', ['teacher_id'], unique=False)
    op.create_index('idx_grades_submission_id', 'grades', ['submission_id'], unique=False)
    op.drop_index(op.f('ix_grade_categories_school_id'), table_name='grade_categories')
    op.drop_index('idx_grade_categories_school', table_name='grade_categories')
    op.create_index('idx_grade_categories_school_id', 'grade_categories', ['school_id'], unique=False)
    op.alter_column('game_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_fee_structures_school_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_assignments_school_id'), table_name='fee_assignments')
    op.drop_index('idx_fee_assignments_fee_structure', table_name='fee_assignments')
    op.create_index('idx_fee_assignments_fee_structure_id', 'fee_assignments', ['fee_structure_id'], unique=False)
    op.drop_index(op.f('ix_events_school_id'), table_name='events')
    op.drop_index(op.f('ix_event_reminder_preferences_school_id'), table_name='event_reminder_preferences')
    op.drop_index(op.f('ix_enrollments_school_id'), table_name='enrollments')
    op.drop_index('idx_enrollments_class', table_name='enrollments')
    op.create_index('idx_enrollments_program_version', 'enrollments', ['program_version_id'], unique=False)
    op.create_index('idx_enrollments_class_id', 'enrollments', ['class_id'], unique=False)
    op.drop_index(op.f('ix_eligibility_rules_school_id'), table_name='eligibility_rules')
    op.drop_index(op.f('ix_documents_school_id'), table_name='documents')
    op.drop_index('idx_doc_versions_uploader_id', table_name='document_versions')
    op.create_index('idx_document_versions_uploader_id', 'document_versions', ['uploader_id'], unique=False)
    op.alter_column('difficulty_adaptations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_device_tokens_school_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_data_exports_school_id'), table_name='data_exports')
    op.drop_index(op.f('ix_curriculum_mappings_school_id'), table_name='curriculum_mappings')
    op.drop_index(op.f('ix_courses_school_id'), table_name='courses')
    op.drop_index('idx_courses_teacher', table_name='courses')
    op.create_index('idx_courses_teacher_id', 'courses', ['teacher_id'], unique=False)
    op.create_index('idx_courses_search', 'courses', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_conversations_school_id'), table_name='conversations')
    op.drop_index(op.f('ix_content_submissions_school_id'), table_name='content_submissions')
    op.drop_index('idx_content_submissions_promoted_content', table_name='content_submissions')
    op.drop_index('idx_content_submissions_content_item', table_name='content_submissions')
    op.create_index('idx_content_submissions_promoted_content_id', 'content_submissions', ['promoted_content_id'], unique=False)
    op.create_index('idx_content_submissions_content_item_id', 'content_submissions', ['content_item_id'], unique=False)
    op.drop_index(op.f('ix_content_manager_profiles_school_id'), table_name='content_manager_profiles')
    op.drop_index(op.f('ix_content_items_school_id'), table_name='content_items')
    op.drop_index('idx_content_items_school', table_name='content_items')
    op.drop_index('idx_content_items_original', table_name='content_items')
    op.create_index('idx_content_items_search', 'content_items', [sa.text("to_tsvector('simple'::regconfig, COALESCE(title, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_content_items_school_id', 'content_items', ['school_id'], unique=False)
    op.create_index('idx_content_items_original_content_id', 'content_items', ['original_content_id'], unique=False)
    op.drop_index('idx_content_item_assets_content_item', table_name='content_item_assets')
    op.create_index('idx_content_item_assets_content_item_id', 'content_item_assets', ['content_item_id'], unique=False)
    op.drop_index(op.f('ix_consent_preferences_school_id'), table_name='consent_preferences')
    op.drop_index(op.f('ix_compliance_reports_school_id'), table_name='compliance_reports')
    op.drop_index('idx_classes_academic_year', table_name='classes')
    op.create_index('idx_classes_academic_year_id', 'classes', ['academic_year_id'], unique=False)
    op.drop_index(op.f('ix_class_content_assignments_school_id'), table_name='class_content_assignments')
    op.drop_index('idx_class_content_assignments_content_item', table_name='class_content_assignments')
    op.create_index('idx_class_content_assignments_content_item_id', 'class_content_assignments', ['content_item_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index('idx_attendance_sessions_teacher', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_period', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_class', table_name='attendance_sessions')
    op.create_index('idx_attendance_sessions_teacher_id', 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_index('idx_attendance_sessions_period_id', 'attendance_sessions', ['period_id'], unique=False)
    op.create_index('idx_attendance_sessions_class_id', 'attendance_sessions', ['class_id'], unique=False)
    op.drop_index(op.f('ix_attendance_records_school_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_alerts_school_id'), table_name='attendance_alerts')
    op.create_index('idx_attendance_alerts_period_id', 'attendance_alerts', ['period_id'], unique=False)
    op.drop_index('idx_assignments_teacher', table_name='assignments')
    op.create_index('idx_assignments_teacher_id', 'assignments', ['teacher_id'], unique=False)
    op.create_index('idx_assignments_search', 'assignments', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_assessments_teacher', table_name='assessments')
    op.create_index('idx_assessments_teacher_id', 'assessments', ['teacher_id'], unique=False)
    op.create_index('idx_assessments_search', 'assessments', [sa.text("to_tsvector('simple'::regconfig, COALESCE(title, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_index('idx_assessment_results_student', table_name='assessment_results')
    op.create_index('idx_assessment_results_student_id', 'assessment_results', ['student_id'], unique=False)
    op.drop_index(op.f('ix_announcements_school_id'), table_name='announcements')
    op.drop_index(op.f('ix_ai_preferences_school_id'), table_name='ai_preferences')
    op.drop_index(op.f('ix_admin_profiles_school_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_activities_school_id'), table_name='activities')
    op.create_index('idx_activities_search', 'activities', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(pedagogical_objective, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_account_recovery_requests_school_id'), table_name='account_recovery_requests')
    op.drop_index('idx_recovery_school_id', table_name='account_recovery_requests')
    op.create_index('idx_account_recovery_requests_school_id', 'account_recovery_requests', ['school_id'], unique=False)
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_index(op.f('ix_academic_snapshots_school_id'), table_name='academic_snapshots')
    op.drop_index('idx_academic_snapshots_taken_at', table_name='academic_snapshots')
    op.create_index('idx_academic_snapshots_taken_at', 'academic_snapshots', ['school_id', sa.text('taken_at DESC')], unique=False)
    op.drop_index('idx_absence_justifications_parent', table_name='absence_justifications')
    op.drop_index('idx_absence_justifications_attendance_record', table_name='absence_justifications')
    op.create_index('idx_absence_justifications_parent_id', 'absence_justifications', ['parent_id'], unique=False)
    op.create_index('idx_absence_justifications_attendance_record_id', 'absence_justifications', ['attendance_record_id'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('upload_state', sa.VARCHAR(length=20), server_default=sa.text("'uploading'::character varying"), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('object_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scope_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('scanned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('target_kind', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='upload_sessions_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='upload_sessions_uploader_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='upload_sessions_pkey'),
    comment='Phase 8: direct-to-MinIO upload lifecycle tracking'
    )
    op.create_index('idx_upload_sessions_uploader', 'upload_sessions', ['uploader_id'], unique=False)
    op.create_index('idx_upload_sessions_state', 'upload_sessions', ['upload_state'], unique=False)
    op.create_index('idx_upload_sessions_school', 'upload_sessions', ['school_id'], unique=False)
    op.create_index('idx_upload_sessions_created', 'upload_sessions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_webauthn_credentials_school_id'), table_name='webauthn_credentials')
    op.drop_index('idx_webauthn_credentials_user', table_name='webauthn_credentials')
    op.drop_index('idx_webauthn_credentials_school', table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_password_history_school_id'), table_name='password_history')
    op.drop_index('idx_password_history_user', table_name='password_history')
    op.drop_index('idx_password_history_school', table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_oauth_accounts_school_id'), table_name='oauth_accounts')
    op.drop_index('idx_oauth_accounts_user', table_name='oauth_accounts')
    op.drop_index('idx_oauth_accounts_school', table_name='oauth_accounts')
    op.drop_index('idx_oauth_accounts_provider', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_known_locations_school_id'), table_name='known_locations')
    op.drop_index('idx_known_locations_user', table_name='known_locations')
    op.drop_index('idx_known_locations_school', table_name='known_locations')
    op.drop_index('idx_known_locations_ip', table_name='known_locations')
    op.drop_table('known_locations')
    op.drop_index(op.f('ix_known_devices_school_id'), table_name='known_devices')
    op.drop_index('idx_known_devices_user', table_name='known_devices')
    op.drop_index('idx_known_devices_school', table_name='known_devices')
    op.drop_index('idx_known_devices_fingerprint', table_name='known_devices')
    op.drop_table('known_devices')
    op.drop_index(op.f('ix_failed_login_attempts_school_id'), table_name='failed_login_attempts')
    op.drop_index('idx_failed_login_attempts_user', table_name='failed_login_attempts')
    op.drop_index('idx_failed_login_attempts_school', table_name='failed_login_attempts')
    op.drop_index('idx_failed_login_attempts_ip', table_name='failed_login_attempts')
    op.drop_index('idx_failed_login_attempts_email', table_name='failed_login_attempts')
    op.drop_table('failed_login_attempts')
    # ### end Alembic commands ###
