"""G1-G6 initial schema: IAM, ERP, LMS, COM, Billing, Audit

Revision ID: 9f7257bc8dd1
Revises: 
Create Date: 2026-03-15 02:47:06.655532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f7257bc8dd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('date_end > date_start', name='ck_academic_years_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_academic_years_school', 'academic_years', ['school_id'], unique=False)
    op.create_table('activities',
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('pedagogical_objective', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_school_type', 'activities', ['school_id', 'type'], unique=False)
    op.create_table('content_items',
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('level_band', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_items_type_level_lang', 'content_items', ['content_type', 'level_band', 'language'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'school_id', name='uq_users_email_school')
    )
    op.create_index('idx_users_school_id', 'users', ['school_id'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('account_recovery_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recovery_user_status', 'account_recovery_requests', ['user_id', 'status'], unique=False)
    op.create_table('activity_sessions',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_sessions_student_activity', 'activity_sessions', ['student_id', 'activity_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('entity_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_actor_action', 'audit_logs', ['actor_id', 'action_type'], unique=False)
    op.create_index('idx_audit_logs_correlation_id', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('idx_audit_logs_school_created', 'audit_logs', ['school_id', 'created_at'], unique=False)
    op.create_table('classes',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'school_id', 'academic_year_id', name='uq_classes_code_school_year')
    )
    op.create_table('consent_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_ref_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic', 'channel', 'scope_type', 'scope_ref_id', name='uq_consent_user_topic_channel_scope')
    )
    op.create_index('idx_consent_school_user', 'consent_preferences', ['school_id', 'user_id'], unique=False)
    op.create_table('content_item_assets',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_progress',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'content_item_id', name='uq_content_progress_student_item')
    )
    op.create_table('invitation_codes',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('issuer_user_id', sa.Uuid(), nullable=True),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('role_target', sa.String(length=10), nullable=False),
    sa.Column('consumed_by', sa.Uuid(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consumed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index('idx_invitation_codes_hash', 'invitation_codes', ['code_hash'], unique=True)
    op.create_index('idx_invitation_codes_school_expires', 'invitation_codes', ['school_id', 'expires_at'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('role_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_memberships_user_school_role_active', 'memberships', ['user_id', 'school_id', 'role_code'], unique=True, postgresql_where="status = 'active'")
    op.create_table('notifications',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('event_ref', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_notifications_school_parent', 'notifications', ['school_id', 'parent_id'], unique=False)
    op.create_table('parent_feed_items',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feed_school_parent_created', 'parent_feed_items', ['school_id', 'parent_id', 'created_at'], unique=False)
    op.create_table('periods',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('date_end > date_start', name='ck_periods_dates'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_periods_school_year', 'periods', ['school_id', 'academic_year_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('revoke_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_correlation_id', 'sessions', ['correlation_id'], unique=False)
    op.create_index('idx_sessions_school_user_active', 'sessions', ['school_id', 'user_id'], unique=False, postgresql_where='revoke_at IS NULL')
    op.create_table('assessments',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total_points >= 0', name='ck_assessments_total_points'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_class_status', 'assessments', ['class_id', 'status'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'session_date', 'slot', name='uq_attendance_sessions_class_date_slot')
    )
    op.create_table('courses',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_school_class', 'courses', ['school_id', 'class_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_enrollments_school_student_period_active', 'enrollments', ['school_id', 'student_id', 'period_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('invoices',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('due_date >= issued_date', name='ck_invoices_due_after_issued'),
    sa.CheckConstraint('total_amount >= 0', name='ck_invoices_total_amount'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoices_parent_status_period', 'invoices', ['parent_id', 'status', 'period_id'], unique=False)
    op.create_index('idx_invoices_school_status', 'invoices', ['school_id', 'status'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deliveries_school_notification_status', 'notification_deliveries', ['school_id', 'notification_id', 'status'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teacher_school_class_period', 'teacher_assignments', ['school_id', 'teacher_id', 'class_id', 'period_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_assessment_results_assessment_student')
    )
    op.create_table('assignments',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total_points >= 0', name='ck_assignments_total_points'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignments_course_due', 'assignments', ['course_id', 'due_at'], unique=False)
    op.create_table('attendance_records',
    sa.Column('attendance_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('absence_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_attendance_records_session_student')
    )
    op.create_index('idx_attendance_records_school_student', 'attendance_records', ['school_id', 'student_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_invoice_items_amount'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_items_quantity'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_attempts',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("NOT (status IN ('paid', 'failed', 'canceled') AND finalized_at IS NULL)", name='ck_payment_attempts_finalization'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_payment_attempts_invoice_created', 'payment_attempts', ['invoice_id', 'created_at'], unique=False)
    op.create_table('absence_justifications',
    sa.Column('attendance_record_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_record_id')
    )
    op.create_table('payment_proofs',
    sa.Column('payment_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('proof_hash', sa.String(length=255), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_attempt_id'),
    sa.UniqueConstraint('proof_hash')
    )
    op.create_table('provider_webhook_events',
    sa.Column('payment_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('signature_status', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_event_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index('idx_webhook_events_school_received', 'provider_webhook_events', ['school_id', 'provider_event_received_at'], unique=False)
    op.create_table('submissions',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_submissions_assignment_student_active', 'submissions', ['assignment_id', 'student_id'], unique=True, postgresql_where="status IN ('draft', 'submitted')")
    op.create_table('grades',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index('idx_grades_submission_published', 'grades', ['submission_id', 'published_at'], unique=False)
    op.create_table('justification_reviews',
    sa.Column('justification_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['justification_id'], ['absence_justifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_files',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_files')
    op.drop_table('justification_reviews')
    op.drop_index('idx_grades_submission_published', table_name='grades')
    op.drop_table('grades')
    op.drop_index('uq_submissions_assignment_student_active', table_name='submissions', postgresql_where="status IN ('draft', 'submitted')")
    op.drop_table('submissions')
    op.drop_index('idx_webhook_events_school_received', table_name='provider_webhook_events')
    op.drop_table('provider_webhook_events')
    op.drop_table('payment_proofs')
    op.drop_table('absence_justifications')
    op.drop_index('idx_payment_attempts_invoice_created', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_table('invoice_items')
    op.drop_index('idx_attendance_records_school_student', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('idx_assignments_course_due', table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('assessment_results')
    op.drop_index('idx_teacher_school_class_period', table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index('idx_deliveries_school_notification_status', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('idx_invoices_school_status', table_name='invoices')
    op.drop_index('idx_invoices_parent_status_period', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('uq_enrollments_school_student_period_active', table_name='enrollments', postgresql_where="status = 'active'")
    op.drop_table('enrollments')
    op.drop_index('idx_courses_school_class', table_name='courses')
    op.drop_table('courses')
    op.drop_table('attendance_sessions')
    op.drop_index('idx_assessments_class_status', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('idx_sessions_school_user_active', table_name='sessions', postgresql_where='revoke_at IS NULL')
    op.drop_index('idx_sessions_correlation_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_periods_school_year', table_name='periods')
    op.drop_table('periods')
    op.drop_index('idx_feed_school_parent_created', table_name='parent_feed_items')
    op.drop_table('parent_feed_items')
    op.drop_index('idx_notifications_school_parent', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_memberships_user_school_role_active', table_name='memberships', postgresql_where="status = 'active'")
    op.drop_table('memberships')
    op.drop_index('idx_invitation_codes_school_expires', table_name='invitation_codes')
    op.drop_index('idx_invitation_codes_hash', table_name='invitation_codes')
    op.drop_table('invitation_codes')
    op.drop_table('content_progress')
    op.drop_table('content_item_assets')
    op.drop_index('idx_consent_school_user', table_name='consent_preferences')
    op.drop_table('consent_preferences')
    op.drop_table('classes')
    op.drop_index('idx_audit_logs_school_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_correlation_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_activity_sessions_student_activity', table_name='activity_sessions')
    op.drop_table('activity_sessions')
    op.drop_index('idx_recovery_user_status', table_name='account_recovery_requests')
    op.drop_table('account_recovery_requests')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index('idx_users_school_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_content_items_type_level_lang', table_name='content_items')
    op.drop_table('content_items')
    op.drop_index('idx_activities_school_type', table_name='activities')
    op.drop_table('activities')
    op.drop_index('idx_academic_years_school', table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
