name: Cleanup old images

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old untagged backend images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}/backend
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: true

      - name: Delete old untagged web images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}/web
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
